
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Get & Cache Dependecies' # required line - title of action in github actions store
description: 'Get the dependencies (via podfile) and cache them' # required line - description of action in github actions store

inputs: # for make custom action more generic
    cachinggg:
        description: 'Whether to cache dependecies or not' # must be added
        required: false # whether this input is needed or not, user must provided this value or not
        # true - user must provide a value in the workflow using this action
        # false - valus is not actually needed, optional
        default: 'true' # can set any value, not only true,false...

outputs:
    used-cachexxx:
        description: 'Whether the cache was used'
        value: ${{ steps.installDpID.outputs.cachexxx }} # assing a value here

runs: # required line
    using: 'composite' # required line - this tells github that this is a custom composite action 
    steps: # required
        - name: Cache dependencies
          if: inputs.cachinggg == 'true' # check default value (true)
          id: cacheID
          uses: actions/cache@v3
          with:
            path: github-actions/Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            # restore-keys: |
            #     ${{ runner.os }}-pods-

        - name: Install pod dependencies
          id: installDepID
          if: steps.cache.outputs.cache-hit != 'true' || inputs.cachinggg != 'true'
          run: | # if you are using run: key - you should add shell: key as well
                cd github-actions
                pod install
                echo "cachexxx=${{ inputs.cachinggg }}" >> $GITHUB_OUTPUT
          shell: bash # bash - which shell environment should be used for this action
