name: Run Unit Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build and Test default scheme using iPhone
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List files in root directory
        run: ls -la

      - name: List files in github-actions directory
        run: |
          cd github-actions
          ls -la

      - name: Install pod dependencies
        run: |
          cd github-actions
          pod install

      - name: Check if .xcworkspace exists
        run: |
             if [ -f "github-actions/github-actions.xcworkspace" ]; then
                echo "Workspace exists"
                else
                 echo "Workspace not found"
                exit 1
             fi

      - name: Set up Xcode 14.3.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Run Unit Tests
        run: |
          cd github-actions
          xcodebuild test \
            -workspace github-actions.xcworkspace \
            -scheme "github-actions" \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT" | xcpretty

      - name: Upload specific file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SingleFileArtifact
          path: |
            github-actions/Info.plist
            github-actions/Helpers
