


name: Cache pod dependecies
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: macos-latest
        outputs:
          cache-hit: ${{ steps.cache.outputs.cache-hit }}
        steps:
        - name: Get code
          uses: actions/checkout@v4

        - name: Cache dependecies
          id: cache
          uses: actions/cache@v4
          with:
            path: |
                Pods
                Podfile.lock
            key: ${{ runner.os }}-pod-${{ hashFiles('**/Podfile.lock') }}

        - name: Install pods
          if: steps.cache.outputs.cache-hit != 'true' # pass this step is cache exist
          run: |
            cd github-actions
            pod install

        - name: Check cache status
          run: echo "Cache status is ${{ steps.cache.outputs.cache-hit }}"

    checkCache:
        runs-on: macos-latest
        needs: build
        steps:
            - name: Check cache status
              if: ${{ needs.build.outputs.cache-hit == 'true' }}
              run: echo "Cache Exist"
