name: Events Demo 1
on:
    pull_request:
    types:
    - opened
    workflow_dispatch: #need to add `:` at the end

jobs:
    outputInfo:
        runs-on: macos-latest
        
        steps:
            - name: Output event details
              run: echo "${{ toJSON(github.event) }}"
    
        
