name: Deployment Execution
on: push

jobs:
  firstJob:
    runs-on: macos-latest
    
    steps:
      - name: Get code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: echo "Install dependencies..."
        
      - name: Build project
        run: echo "Build project..."
       
      - name: Deploy project
        run: echo "Deploy project..."
        
  secondJob:
    runs-on: macos-latest
    needs: firstJob
    
    steps:
        - name: Show in console
          run: echo "Show in console..."
          
