name: Test Project
on: push
jobs:
    test-job:
        runs-on: macos-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
              
    first-job:
        runs-on: macos-latest

    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye!"
            
              
              
        
