name: Matrix
on:
    push:
        branches:
            - main

jobs:
    build:
        continue-on-error: true
        # allows to continue execute all the jobs that related to this matrix even if some jobs for some combination failed
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operation-system: [ubuntu-latest, macos-latest]
                # include, exclude - reserved key
                include: # use key values you defined in matrix
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude:
                    - node-version: 12
                      operating-system: macos-latest
                    
                
        runs-on: ${{ matrix.operation-system }}
        steps:
        - name: Get code
          uses: actions/checkout@v3
          #with:
            #node-version: ${{ matrix.node-version }}
          
        - name: List resources
          run: echo 'List resources'


                
                
                
                
                
                
                
                
                
                

