name: Label Issues (Script Injection Example)
on:
  issues
    # types:
    #   - opened
    #   - labeled
  #push

jobs:
  assign_label:
    runs-on: macos-latest
    steps:
      - name: Assign Label
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          if [[ "$ISSUE_TITLE" == *"bug"* ]]; then
            echo "Issue is about a bug!"
          else
            echo "Issue is not about a bug"
          fi
