name: Using reusable workflow

on:
    push:
        branches:
         - dev

jobs:
    start:
        runs-on: macos-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: List directory contents
          run: ls -la

        - name: Archive artifact
          uses: actions/upload-artifact@v3
          with:
            name: ios-info-files
            path: ./github-actions/Resources/configuration.json

        - name: Check if artifact exists
          run: |
                if [ ! -f ./github-actions/Resources/configuration.json ]; then
                  echo "Artifact not found!"
                  exit 1
                fi

    deploy:
        needs: start
        uses: ./.github/workflows/reusable.yml
        with:
            artifact-name: ios-info-files
        # secretes:
        #   some-secret: ${{ secrets.some-secret }}

    print-deploy-result:
        needs: deploy
        runs-on: macos-latest
        steps:
        - name: Print deploy output LAST
          run: echo "${{ needs.deploy.outputs.resultee }}"
